---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Ensure the myns-atin Namespace exists.
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: myns-atin
        state: present



# How to run:
# ansible-playbook 1.Create-namespace.yml
# sudo kubectl get all
