---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Ensure the myapp Namespace exists.
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: atintesting
        state: present

    - name: Remove an existing Service object
      community.kubernetes.k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: testing
        name: web

# How to run:
# ansible-playbook 4.Remove-service-with-Ansible.yml
# sudo kubectl get service
