---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      community.kubernetes.helm:
        name: test
        release_namespace: monitoring
        state: absent
        wait: true

# How to run
# ansible-playbook 3.remove-helm-release.yml
# kubectl get ns
# kubectl get pods --namespace=monitoring
