---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      community.kubernetes.helm:
        name: test
        chart_ref: stable/prometheus
        release_namespace: monitoring
        create_namespace: true

# How to run
# ansible-playbook 1.helm.yml
# kubectl get ns
# kubectl get pods --namespace=monitoring
