---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      community.kubernetes.helm:
        name: test
        chart_ref: stable/prometheus
        release_namespace: atin-monitoring-prometheus
        state: present
        create_namespace: true

# How to run
# Change the value of release_namespace
# ansible-playbook 1.helm.yml
# kubectl get ns
# kubectl get pods --namespace=atin-monitoring-prometheus
# helm repo list
# helm list -n atin-monitoring-prometheus
# helm history test  -n atin-monitoring-prometheus
# kubectl delete ns atin-monitoring-prometheus
